version: "3"
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: server
    env_file:
      - ./app/server/.env
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    ports:
      - "5000:5000"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: 'redis:latest'
    container_name: "redis_server"
  db:
      image: mysql:5.7
      container_name: "MySQL_Database_Flask"
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile.dev
#    volumes:
#      - ./client:/app
#      - /client/node_modules
#    ports:
#      - "3000:3000"
#    stdin_open: true
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    depends_on:
#      - api
#      - client
#    restart: always
#    volumes:
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - "8081:81"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    restart: always
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - /sessions